---
deployment:
  tasks:
    - export DEPLOYPATH=/home/elitccyv/e-fix
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan config:clear
    - cd $DEPLOYPATH && php artisan cache:clear
    - cd $DEPLOYPATH && php artisan view:clear